import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ConfigProvider } from "antd";

export const metadata = {
  title: {
    template: '%s | Elucdator',
    default: "Elucidator"
  },
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh">
      <body>
        <ConfigProvider
        theme={{
          token:{
            fontFamily: 'jiangxizhuokai'
          }
        }}>
          <Navbar />
          <div className="container">
            {children}
          </div>
          <Footer />
        </ConfigProvider>
      </body>
    </html>
  );
}
